#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "155px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Ceph.id"
# purgeCSS
purge_css = true
# image gallery shortcode
image_gallery = true
# contact form action
contact_form_action = "https://formspree.io/f/xgebwpbo" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
theme_copyright = false
copyright = "Copyright Â© [Ceph Indonesia Community](https://ceph.id)"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[[nav_button]]
style = "outline"   # available style: solid, outline
label = "Events"
link = "events/"

[[nav_button]]
style = "solid"   # available style: solid, outline
label = "Contact"
link = "contact/"

# Crisp Chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Ceph", "Storage", "SDS", "Data"]
description = "Massively scalable, open source, distributed storage system."
author = "Saputro Aryulianto"
image = "images/favicon.png"      # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = ""       # your matomo url
id = ""        # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = ""    # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = ""  # your username

# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon : https://fontawesome.com/icons
link = "https://facebook.com/openinfraid"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon : https://fontawesome.com/icons
link = "https://twitter.com/openinfraid"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon : https://fontawesome.com/icons
link = "https://instagram.com/openinfraid"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon : https://fontawesome.com/icons
link = "https://github.com/openinfraid"
